name: Convert ENV to YAML

on:
  push:
    branches: [main]

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install PyYAML

      - name: Debug input files
        run: |
          echo "Contents of ENV_FILES:"
          ls -la ENV_FILES/

      - name: Run conversion script
        run: python env_to_yaml.py

      - name: Debug output files
        run: |
          echo "Contents of ConvertedYaml:"
          ls -la ConvertedYaml/

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          
          # Add all changes
          git add ConvertedYaml/
          
          # Check for changes
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git commit -m "Auto-commit converted YAML files [$(date +'%Y-%m-%d %H:%M:%S')]"
            git pull --rebase
            git push origin main
          fi